### ISSUE TITLE
Minimum active extension of poly 

### ISSUE THREAD

**Issue by arugak** [MakeLSI/OpenRule1um#1]
qflowの実験のために、セルセットのLEFを作ろうとしています。

ドレイン・ソースの最小幅なのですが、細くしてもエラーにならないです。
https://1drv.ms/u/s!Ap5iDg6OrBeiqRTw80PCpJlV6euZ

これは、いくらが最小でしょうか？
DRCに実装するのは難しいですか？

**Comment by akita11** [comment]
ああ、これはルールに書いてなかったかもです。いっしょにおいてあるExcelファイルをみていただけますか。（抜けがあるかもなので、MLで話を出していただけると）
あとスタセルですが、3月末あたりをめどに、山田さん＠ALSIが、スタセルを作ってくれる予定（0.5umルールにこだわらずに、できるだけ小さくできるやつ）で、その後、それからLEFを作ろうかと考えています。なので、いまやっていただくと二度手間にならないかな、という心配をしています。せめて最低限のスタセルにしませんか？

**Comment by arugak** [comment]
了解です。クローズしてください。
こちらはとりあえず、LEFに要るメタルだけ描いて、実験しようとしてます。
nand2, nor2, inv, dffの４つだけ。
バルクは描いてみよっかなと思ったところでした。
