### ISSUE TITLE
README.md内のGladeのバージョン

### ISSUE THREAD

**Issue by watari3** [MakeLSI/OpenRule1um#14]
## 詳細
README.mdを参考にGladeを使おうとしていますが、
記載されているような項目がなさそうに見受けられます。
説明を記載する際に使用したGladeのバージョンは何でしょうか

## 関連するissue
なし

## 備考
なし

**Comment by akita11** [comment]
具体的に何がないかをあげてください。（さきほど作業したのはGlade v4.7.8でした）

**Comment by watari3** [comment]
README.mdやREADME_cell.mdを書かれたときに使用していたバージョンもv4.7.8でしょうか？

問題点については画像つきで書き込みますのでしばらくお待ち下さい。

**Comment by watari3** [comment]
README.md及びREADME_cell.mdを参考に作業を行おうとしました。

1. Gladeを起動し、OpenRule1umライブラリを開く
とのことでしたので、下記の左から2番目のアイコンをクリックしglade.libファイルがあるディレクトリを選択しました。
- 起動後画面
![glade-start-screen](https://user-images.githubusercontent.com/22569573/59563975-ddea2e80-907b-11e9-8c58-092baaa4f1c8.png)

2. Edit -> Display Option(E)を開き、Display Setting内のDisplay Grid、Snap Gridを、いずれも「0.06625」に設定する（※0.0625=1/16）
とのことですがEditというものはありませんし、File、Tools、Windowの中を探しても見当たりません。

- ロード後画面
![glade-load-library](https://user-images.githubusercontent.com/22569573/59564007-46d1a680-907c-11e9-9bb5-77d100ae498d.png)

Q1) 使用しているツールはGlade release version 4.7.8であり同一ですが記載してあるようなEdit -> Display Optionがありません。これはどこにあるのでしょうか。

**Comment by akita11** [comment]
記述が間違っていたので修正してcommitしました（schematicを開いた状態で、View→Display Options、が正しい）
