### ISSUE TITLE
論理セル作成状況まとめ

### ISSUE THREAD

**Issue by watari3** [MakeLSI/OpenRule1um#4]
## 詳細
作成しなければいけない論理セル一覧をまとめる

## 論理セル作成進捗状況
- [x] an21 ( #5 )
- [x] an31 ( #6 )
- [x] an41 ( #7 )
- [x] buf1 ( #8 )
- [x] buf2 ( #9 )
- [x] buf4 ( #10 )
- [x] buf8 ( #11 )
- [x] cellall
- [x] cinv
- [x] dcont
- [x] dff1
- [x] dff1m2
- [x] exnr (#20)
- [x] exor (#19)
- [x] inv1
- [x] inv2
- [x] inv4
- [x] inv8
- [x] na21 ( #12 )
- [x] na31
- [x] na41
- [x] na212
- [x] na222
- [x] nch
- [ ] nr21
- [ ] nr31
- [x] nr212
- [x] nr222
- [x] nsubcont
- [ ] or21
- [ ] or31
- [x] pch
- [x] pcont
- [x] psubcont
- [x] rff1
- [x] rff1m2
- [x] sff1
- [x] sff1m2
- [x] Via

## 関連するissue
なし

**Comment by akita11** [comment]
あとはwatari3作のnr21,or21のsymをマージし、そこからnr31,or31を作成したら完成
